/*
 * chip8_utils - CHIP8 Interpreter Utilities
 *
 * Mike Mallin, 2020
 */

#ifndef __CHIP8_UTILS_H__
#define __CHIP8_UTILS_H__

#include <stdint.h>

/**
 * @brief      Gets a randomly generated byte.
 *
 * @return     The random byte.
 */
uint8_t get_random_byte(void);

#endif /* __CHIP8_UTILS_H__ */
