name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Enable universe Apt repository (For cmocka)
      run: sudo add-apt-repository universe
    - name: Apt Update
      run: sudo apt-get update -qq
    - name: Install libsdl2 dependencies
      run: sudo apt-get install libegl1-mesa-dev libgles2-mesa-dev
    - name: Install Dependencies
      run: sudo apt-get install libsdl2-dev lcov libcmocka-dev
    - name: Show GCC Version
      run: gcc --version
    - name: Build Production
      run: make
    - name: Build and run Unit Tests
      run: make check
    - name: Generate Coverage
      run: make lcov
